/** Automação do Sorteio de Vôlei — V003 */
const VOLEI_AUTOMACAO=Object.freeze({VERSION:'V003_ADULTOS_CRIANCAS_INSCRICAO_2026-07-21',TRIGGER_FUNCTION:'VERIFICAR_SORTEIO_AUTOMATICO',INTERVAL_MINUTES:1});
function onOpen(){try{SpreadsheetApp.getUi().createMenu('🏐 Sorteio de Vôlei').addItem('Instalar sistema completo','INSTALAR_SISTEMA_COMPLETO').addItem('Instalar acionador automático','INSTALAR_ACIONADOR_SORTEIO').addItem('Executar diagnóstico','DIAGNOSTICO_COMPLETO').addSeparator().addItem('Realizar sorteio de teste agora','REALIZAR_SORTEIO_TESTE_AGORA').addItem('Remover acionadores','REMOVER_ACIONADORES_SORTEIO').addToUi()}catch(err){console.log('Menu não disponível neste contexto: '+mensagemErro_(err))}}
function INSTALAR_SISTEMA_COMPLETO(){const config=CONFIGURAR_SISTEMA_INICIAL(),estrutura=validarEstruturaSistema_(),trigger=instalarAcionadorSorteio_();atualizarConfigSistema_('VERSAO',VOLEI_AUTOMACAO.VERSION,'Versão instalada');atualizarConfigSistema_('ACIONADOR_AUTOMATICO','ATIVO','Verificação automática a cada minuto');atualizarConfigSistema_('ULTIMA_VERIFICACAO',formatarData_(new Date()),'Última instalação ou verificação');log_('SISTEMA_INSTALADO','','EDITOR_APPS_SCRIPT',Session.getEffectiveUser().getEmail()||'ADMIN',JSON.stringify({estrutura:estrutura,trigger:trigger}));const r={ok:true,mensagem:'Sistema configurado e acionador automático instalado.',versao:VOLEI_AUTOMACAO.VERSION,adminKey:config.adminKey,spreadsheetId:config.spreadsheetId,acionador:trigger,estrutura:estrutura};Logger.log(JSON.stringify(r,null,2));return r}
function INSTALAR_ACIONADOR_SORTEIO(){const r=instalarAcionadorSorteio_();atualizarConfigSistema_('ACIONADOR_AUTOMATICO','ATIVO','Verificação automática a cada minuto');Logger.log(JSON.stringify(r,null,2));return r}
function instalarAcionadorSorteio_(){removerAcionadoresPorFuncao_(VOLEI_AUTOMACAO.TRIGGER_FUNCTION);const t=ScriptApp.newTrigger(VOLEI_AUTOMACAO.TRIGGER_FUNCTION).timeBased().everyMinutes(VOLEI_AUTOMACAO.INTERVAL_MINUTES).create();return{funcao:VOLEI_AUTOMACAO.TRIGGER_FUNCTION,intervaloMinutos:VOLEI_AUTOMACAO.INTERVAL_MINUTES,triggerId:t.getUniqueId()}}
function REMOVER_ACIONADORES_SORTEIO(){const r=removerAcionadoresPorFuncao_(VOLEI_AUTOMACAO.TRIGGER_FUNCTION);atualizarConfigSistema_('ACIONADOR_AUTOMATICO','INATIVO','Acionador automático removido');return{ok:true,removidos:r}}
function removerAcionadoresPorFuncao_(f){let r=0;ScriptApp.getProjectTriggers().forEach(t=>{if(t.getHandlerFunction()===f){ScriptApp.deleteTrigger(t);r++}});return r}
function VERIFICAR_SORTEIO_AUTOMATICO(){try{verificarSorteioVencido_();atualizarConfigSistema_('ULTIMA_VERIFICACAO',formatarData_(new Date()),'Última execução do acionador');return{ok:true,status:(ultimoSorteio_()||{}).status||'SEM_SORTEIO'}}catch(err){try{log_('ERRO_ACIONADOR','','ACIONADOR_MINUTO','SISTEMA',mensagemErro_(err))}catch(ignore){}console.error(err);return{ok:false,erro:mensagemErro_(err)}}}
function validarEstruturaSistema_(){const r={ok:true,abas:{}};Object.keys(VOLEI.HEADERS).forEach(k=>{const n=VOLEI.SHEETS[k]||k,s=ss_().getSheetByName(n),e=VOLEI.HEADERS[k];if(!s){r.ok=false;r.abas[n]={ok:false,erro:'Aba não encontrada'};return}const a=s.getRange(1,1,1,Math.min(e.length,s.getMaxColumns())).getDisplayValues()[0],d=e.filter((h,i)=>a[i]!==h);r.abas[n]={ok:d.length===0,colunas:e.length,divergencias:d};if(d.length)r.ok=false});return r}
function atualizarConfigSistema_(chave,valor,descricao){const s=aba_(VOLEI.SHEETS.CONFIG),l=Math.max(4,s.getLastRow()),v=l>=5?s.getRange(5,1,l-4,1).getDisplayValues().flat():[],i=v.indexOf(chave);if(i>=0)s.getRange(i+5,2,1,2).setValues([[valor,descricao||'']]);else s.appendRow([chave,valor,descricao||''])}
function DIAGNOSTICO_COMPLETO(){const t=ScriptApp.getProjectTriggers().filter(x=>x.getHandlerFunction()===VOLEI_AUTOMACAO.TRIGGER_FUNCTION).map(x=>({id:x.getUniqueId(),funcao:x.getHandlerFunction()})),e=validarEstruturaSistema_(),potes=(()=>{try{const v=validarPotes_();return{ok:true,adultos:v.a.length,criancas:v.b.length}}catch(err){return{ok:false,erro:mensagemErro_(err)}}})(),r={ok:e.ok&&t.length>0,versaoBackend:VOLEI.VERSION,versaoAutomacao:VOLEI_AUTOMACAO.VERSION,planilha:ss_().getUrl(),estrutura:e,potes:potes,acionadores:t};Logger.log(JSON.stringify(r,null,2));return r}