/** Cadastro, idade, categorias e notas */
function normalizarNome_(v){const c=['de','da','do','das','dos','e'];return texto_(v).replace(/\s+/g,' ').toLocaleLowerCase('pt-BR').split(' ').map((p,i)=>i&&c.indexOf(p)>=0?p:(p?p.charAt(0).toLocaleUpperCase('pt-BR')+p.slice(1):'')).join(' ')}
function interpretarDataNascimento_(v){if(v instanceof Date&&!isNaN(v.getTime()))return v;const s=texto_(v);let m;if((m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/)))return new Date(+m[1],+m[2]-1,+m[3]);if((m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/)))return new Date(+m[3],+m[2]-1,+m[1]);const d=new Date(s);return isNaN(d.getTime())?null:d}
function calcularIdade_(v,h){const n=interpretarDataNascimento_(v),d=h||new Date();if(!n)return-1;let a=d.getFullYear()-n.getFullYear();if(d.getMonth()<n.getMonth()||(d.getMonth()===n.getMonth()&&d.getDate()<n.getDate()))a--;return a}
function classificarPorIdade_(a){return a>=18?{pote:'A',categoria:'ADULTO',rotulo:'Adulto'}:{pote:'B',categoria:'CRIANCA',rotulo:'Criança'}}
function calcularNotaAjustada_(n){n=numero_(n);if(n===5)return 7.5;if(n===4)return 6.8;if(n===3)return 6;if(n===2||n===1||n===0)return 8;return n}
function validarDadosParticipante_(p){const n=normalizarNome_(p.nome),dn=interpretarDataNascimento_(p.dataNascimento),i=calcularIdade_(dn),nt=numero_(p.nota),cl=classificarPorIdade_(i),at=texto_(p.ativo||'SIM').toUpperCase();if(n.length<2)throw Error('Informe o nome do participante.');if(!dn||i<0||i>100)throw Error('Informe uma data de nascimento válida.');if(Math.floor(nt)!==nt||nt<0||nt>10)throw Error('A nota de desempenho deve ser um número inteiro de 0 a 10.');if(cl.pote==='A'&&nt<5)throw Error('Para adultos, a nota mínima de desempenho é 5.');if(['SIM','NAO'].indexOf(at)<0)throw Error('O campo ATIVO deve ser SIM ou NAO.');return{nome:n,dataNascimento:dn,idade:i,pote:cl.pote,categoria:cl.categoria,rotulo:cl.rotulo,nota:nt,notaAjustada:calcularNotaAjustada_(nt),ativo:at}}
function lerJogadores_(){const s=aba_(VOLEI.SHEETS.JOGADORES),l=s.getLastRow();if(l<2)return[];return s.getRange(2,1,l-1,VOLEI.HEADERS.JOGADORES.length).getValues().filter(r=>r[0]||r[1]).map(r=>({id:texto_(r[0]),nome:texto_(r[1]),dataNascimento:r[2],idade:numero_(r[3]),pote:texto_(r[4]).toUpperCase(),categoria:texto_(r[5]),nota:numero_(r[6]),notaAjustada:numero_(r[7]),ativo:texto_(r[8]||'SIM').toUpperCase(),dataCadastro:r[9],observacao:texto_(r[10])}))}
function proximoIdJogador_(p){const u=lerJogadores_().filter(x=>x.pote===p).map(x=>Number((x.id.match(/(\d+)$/)||[0,0])[1]));return p+'-'+('000'+((u.length?Math.max.apply(null,u):0)+1)).slice(-3)}
function participanteDuplicado_(id,n,d){const k=formatarDataNascimento_(d);return lerJogadores_().some(p=>p.id!==id&&normalizarNome_(p.nome)===n&&p.dataNascimento&&formatarDataNascimento_(interpretarDataNascimento_(p.dataNascimento))===k)}
function inscreverParticipante_(p){const a=ultimoSorteio_();if(a&&['EM_CONTAGEM','SORTEADO'].indexOf(a.status)>=0)throw Error('As inscrições estão encerradas para o sorteio atual.');p.id='';p.ativo='SIM';const r=salvarParticipante_(p,false);r.mensagem='Inscrição confirmada no Pote '+r.jogador.pote+' — '+r.jogador.rotuloCategoria+'.';return r}
function salvarParticipante_(p,admin){const d=validarDadosParticipante_(p),s=aba_(VOLEI.SHEETS.JOGADORES);let id=admin?texto_(p.id):'';if(!id)id=proximoIdJogador_(d.pote);if(participanteDuplicado_(id,d.nome,d.dataNascimento))throw Error('Este participante já está inscrito.');const l=s.getLastRow();let row=0;if(l>=2){const ids=s.getRange(2,1,l-1,1).getDisplayValues().flat(),i=ids.indexOf(id);if(i>=0)row=i+2}const a=row?s.getRange(row,1,1,VOLEI.HEADERS.JOGADORES.length).getValues()[0]:[],v=[id,d.nome,d.dataNascimento,d.idade,d.pote,d.categoria,d.nota,d.notaAjustada,admin?d.ativo:'SIM',a[9]||new Date(),texto_(p.observacao||a[10])];row?s.getRange(row,1,1,v.length).setValues([v]):s.appendRow(v);invalidarSorteioPorCadastro_('Participante salvo: '+d.nome);log_('PARTICIPANTE_SALVO','',admin?'PAINEL_WEB':'SITE_PUBLICO',admin?'ADMIN':'INSCRICAO',id+' | '+d.nome+' | '+d.categoria+' | Nota '+d.nota+' | Índice '+d.notaAjustada);return{mensagem:'Participante salvo.',jogador:{id:id,nome:d.nome,dataNascimento:formatarDataNascimento_(d.dataNascimento),idade:d.idade,pote:d.pote,categoria:d.categoria,rotuloCategoria:d.rotulo,nota:d.nota,notaAjustada:d.notaAjustada,ativo:admin?d.ativo:'SIM'},estado:obterEstadoAdminSemVerificacao_()}}
function excluirParticipante_(id){id=texto_(id);if(!id)throw Error('ID do participante não informado.');const s=aba_(VOLEI.SHEETS.JOGADORES),l=s.getLastRow();if(l<2)throw Error('Participante não encontrado.');const ids=s.getRange(2,1,l-1,1).getDisplayValues().flat(),i=ids.indexOf(id);if(i<0)throw Error('Participante não encontrado: '+id);const n=s.getRange(i+2,2).getDisplayValue();s.deleteRow(i+2);invalidarSorteioPorCadastro_('Participante excluído: '+n);log_('PARTICIPANTE_EXCLUIDO','','PAINEL_WEB','ADMIN',id+' | '+n);return{mensagem:'Participante excluído.',estado:obterEstadoAdminSemVerificacao_()}}
function invalidarSorteioPorCadastro_(m){limparDadosAbaixoCabecalho_(VOLEI.SHEETS.EQUIPES,VOLEI.HEADERS.EQUIPES.length);limparDadosAbaixoCabecalho_(VOLEI.SHEETS.CHAVEAMENTO,VOLEI.HEADERS.CHAVEAMENTO.length);aba_(VOLEI.SHEETS.SORTEIOS).appendRow([gerarId_('SOR'),'RASCUNHO','','',new Date(),'','','','','','SISTEMA',m])}
function validarPotes_(){const a=lerJogadores_().filter(p=>p.ativo==='SIM'),x=a.filter(p=>p.pote==='A'),y=a.filter(p=>p.pote==='B');if(x.length!==y.length)throw Error('A quantidade precisa ser igual. Adultos: '+x.length+'; crianças: '+y.length+'.');if(x.length<2)throw Error('São necessários pelo menos dois adultos e duas crianças.');return{a:x,b:y}}