/** Chaveamento, placares e intervalo entre partidas — V004 */
const CHAVEAMENTO_HEADERS_V004=['SORTEIO_ID','JOGO','FASE','EQUIPE_1_ID','EQUIPE_1','EQUIPE_2_ID','EQUIPE_2','SET1_EQ1','SET1_EQ2','SET2_EQ1','SET2_EQ2','SET3_EQ1','SET3_EQ2','SETS_EQ1','SETS_EQ2','VENCEDOR_ID','STATUS','FIM_PARTIDA','DISPONIVEL_EM','RODADA_INDEX','PROXIMO_JOGO','PROXIMO_SLOT'];
function embaralharDeterministico_(lista,seed){const a=lista.slice();let e=parseInt(hash_(seed).slice(0,8),16)>>>0;function r(){e+=0x6D2B79F5;let t=e;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1)),x=a[i];a[i]=a[j];a[j]=x}return a}
function proximaPotenciaDois_(n){let p=1;while(p<Math.max(2,n))p*=2;return p}
function nomeFase_(size,round,total){const restantes=size/Math.pow(2,round+1);if(round===total-1)return'FINAL';if(restantes===2)return'SEMIFINAL';if(restantes===4)return'QUARTAS DE FINAL';if(restantes===8)return'OITAVAS DE FINAL';return'RODADA '+(round+1)}
function montarChaveamento_(equipes){const size=proximaPotenciaDois_(equipes.length),total=Math.log(size)/Math.log(2),slots=equipes.slice(),rounds=[];while(slots.length<size)slots.push(null);let jogo=1;for(let r=0;r<total;r++){const count=size/Math.pow(2,r+1),matches=[];for(let i=0;i<count;i++)matches.push({game:jogo++,roundIndex:r,phase:nomeFase_(size,r,total),team1:null,team2:null,team1Placeholder:'',team2Placeholder:'',scores:[null,null,null],sets1:0,sets2:0,winnerId:'',status:'AGUARDANDO',finishedAt:'',availableAt:'',nextGame:0,nextSlot:0});rounds.push({index:r,name:nomeFase_(size,r,total),matches:matches})}for(let i=0;i<rounds[0].matches.length;i++){const m=rounds[0].matches[i];m.team1=slots[i*2];m.team2=slots[i*2+1];if(m.team1&&!m.team2){m.winnerId=m.team1.id;m.status='BYE'}else if(!m.team1&&m.team2){m.winnerId=m.team2.id;m.status='BYE'}else if(!m.team1&&!m.team2)m.status='VAZIO'}for(let r=0;r<rounds.length-1;r++)rounds[r].matches.forEach((m,i)=>{const next=rounds[r+1].matches[Math.floor(i/2)];m.nextGame=next.game;m.nextSlot=i%2===0?1:2;if(m.winnerId)atribuirVencedorMemoria_(rounds,m)});for(let r=1;r<rounds.length;r++)rounds[r].matches.forEach((m,i)=>{const p1=rounds[r-1].matches[i*2],p2=rounds[r-1].matches[i*2+1];if(!m.team1)m.team1Placeholder='Vencedor Jogo '+p1.game;if(!m.team2)m.team2Placeholder='Vencedor Jogo '+p2.game});return rounds}
function atribuirVencedorMemoria_(rounds,match){if(!match.nextGame||!match.winnerId)return;let next=null;for(let r=0;r<rounds.length;r++){next=rounds[r].matches.filter(m=>m.game===match.nextGame)[0];if(next)break}if(!next)return;const team=match.team1&&match.team1.id===match.winnerId?match.team1:match.team2;if(match.nextSlot===1)next.team1=team;else next.team2=team}
function nomeEquipe_(e){return e?e.adulto+' + '+e.crianca:''}
function garantirEstruturaChaveamentoV004_(){const s=aba_(VOLEI.SHEETS.CHAVEAMENTO);if(s.getMaxColumns()<CHAVEAMENTO_HEADERS_V004.length)s.insertColumnsAfter(s.getMaxColumns(),CHAVEAMENTO_HEADERS_V004.length-s.getMaxColumns());s.getRange(1,1,1,CHAVEAMENTO_HEADERS_V004.length).setValues([CHAVEAMENTO_HEADERS_V004]);return s}
function gravarEquipes_(equipes){const s=aba_(VOLEI.SHEETS.EQUIPES);limparDadosAbaixoCabecalho_(VOLEI.SHEETS.EQUIPES,12);if(!equipes.length)return;s.getRange(2,1,equipes.length,12).setValues(equipes.map(e=>[e.id,e.adultoId,e.adulto,e.notaAdulto,e.indiceAdulto,e.criancaId,e.crianca,e.notaCrianca,e.indiceCrianca,e.indiceTotal,e.ordemBalanceamento,e.ordemChaveamento]))}
function gravarChaveamento_(sorteioId,rounds){const s=garantirEstruturaChaveamentoV004_();limparDadosAbaixoCabecalho_(VOLEI.SHEETS.CHAVEAMENTO,CHAVEAMENTO_HEADERS_V004.length);const rows=[];rounds.forEach(round=>round.matches.forEach(m=>rows.push([sorteioId,m.game,m.phase,m.team1?m.team1.id:'',m.team1?nomeEquipe_(m.team1):m.team1Placeholder,m.team2?m.team2.id:'',m.team2?nomeEquipe_(m.team2):m.team2Placeholder,'','','','','','',0,0,m.winnerId||'',m.status||'AGUARDANDO','','',m.roundIndex,m.nextGame||'',m.nextSlot||''])));if(rows.length){s.getRange(2,1,rows.length,CHAVEAMENTO_HEADERS_V004.length).setValues(rows);liberarPrimeiraPartida_()}}
function lerEquipes_(){const s=aba_(VOLEI.SHEETS.EQUIPES),l=s.getLastRow();if(l<2)return[];return s.getRange(2,1,l-1,12).getValues().filter(r=>r[0]).map(r=>({id:texto_(r[0]),adultoId:texto_(r[1]),adulto:texto_(r[2]),notaAdulto:numero_(r[3]),indiceAdulto:numero_(r[4]),criancaId:texto_(r[5]),crianca:texto_(r[6]),notaCrianca:numero_(r[7]),indiceCrianca:numero_(r[8]),indiceTotal:numero_(r[9]),ordemBalanceamento:numero_(r[10]),ordemChaveamento:numero_(r[11])}))}
function lerRounds_(){const s=garantirEstruturaChaveamentoV004_(),l=s.getLastRow();if(l<2)return[];const rows=s.getRange(2,1,l-1,CHAVEAMENTO_HEADERS_V004.length).getValues().filter(r=>r[0]),eq={};lerEquipes_().forEach(e=>eq[e.id]=e);const g={};rows.forEach(r=>{const i=numero_(r[19]);if(!g[i])g[i]={index:i,name:texto_(r[2])||'RODADA '+(i+1),matches:[]};g[i].matches.push({game:numero_(r[1]),roundIndex:i,phase:texto_(r[2]),team1:r[3]?eq[texto_(r[3])]||{id:texto_(r[3]),nome:texto_(r[4])}:null,team2:r[5]?eq[texto_(r[5])]||{id:texto_(r[5]),nome:texto_(r[6])}:null,team1Placeholder:!r[3]?texto_(r[4]):'',team2Placeholder:!r[5]?texto_(r[6]):'',scores:[[valorPlacar_(r[7]),valorPlacar_(r[8])],[valorPlacar_(r[9]),valorPlacar_(r[10])],[valorPlacar_(r[11]),valorPlacar_(r[12])]],sets1:numero_(r[13]),sets2:numero_(r[14]),winnerId:texto_(r[15]),status:texto_(r[16]),finishedAt:r[17]||'',availableAt:r[18]||'',nextGame:numero_(r[20]),nextSlot:numero_(r[21])})});return Object.keys(g).map(Number).sort((a,b)=>a-b).map(k=>g[k])}
function valorPlacar_(v){return v===''||v===null?null:numero_(v)}
function validarSetOficial_(a,b,alvo,numeroSet){if(a===null||b===null)throw Error('Preencha a pontuação do '+numeroSet+'º set.');if(a<0||b<0||Math.floor(a)!==a||Math.floor(b)!==b)throw Error('A pontuação dos sets deve usar números inteiros não negativos.');if(a===b)throw Error('O '+numeroSet+'º set não pode terminar empatado.');const maior=Math.max(a,b),dif=Math.abs(a-b);if(maior<alvo||dif<2)throw Error('Placar inválido no '+numeroSet+'º set. O vencedor precisa atingir '+alvo+' pontos e abrir vantagem mínima de 2.');return a>b?1:2}
function validarPlacarMelhorDeTres_(s1a,s1b,s2a,s2b,s3a,s3b){const w1=validarSetOficial_(s1a,s1b,21,1),w2=validarSetOficial_(s2a,s2b,21,2);let sets1=(w1===1?1:0)+(w2===1?1:0),sets2=(w1===2?1:0)+(w2===2?1:0),w3=0;if(sets1===1&&sets2===1){w3=validarSetOficial_(s3a,s3b,15,3);if(w3===1)sets1++;else sets2++}else if((s3a!==null&&s3a!==0)||(s3b!==null&&s3b!==0))throw Error('O 3º set só deve ser preenchido quando a partida estiver empatada em 1 set a 1.');return{sets1:sets1,sets2:sets2,vencedorLado:sets1===2?1:2}}
function liberarPrimeiraPartida_(){const s=garantirEstruturaChaveamentoV004_(),l=s.getLastRow();if(l<2)return;const d=s.getRange(2,1,l-1,CHAVEAMENTO_HEADERS_V004.length).getValues(),i=d.findIndex(r=>r[3]&&r[5]&&texto_(r[16])==='AGUARDANDO');if(i>=0)s.getRange(i+2,19).setValue(new Date())}
function liberarProximaPartida_(dados,ignorarIndice,quando){const s=garantirEstruturaChaveamentoV004_();for(let i=0;i<dados.length;i++){if(i===ignorarIndice)continue;const r=dados[i],status=texto_(r[16]);if(r[3]&&r[5]&&status==='AGUARDANDO'&&!r[18]){s.getRange(i+2,19).setValue(quando);return}}
}
function registrarResultado_(jogo,payload){jogo=numero_(jogo);payload=texto_(payload);if(!jogo)throw Error('Informe o jogo.');if(payload.indexOf('PLACAR|')!==0)throw Error('Preencha a pontuação dos sets antes de salvar.');const p=payload.split('|'),s1a=numeroOpcional_(p[1]),s1b=numeroOpcional_(p[2]),s2a=numeroOpcional_(p[3]),s2b=numeroOpcional_(p[4]),s3a=numeroOpcional_(p[5]),s3b=numeroOpcional_(p[6]);const resultado=validarPlacarMelhorDeTres_(s1a,s1b,s2a,s2b,s3a,s3b),s=garantirEstruturaChaveamentoV004_(),l=s.getLastRow();if(l<2)throw Error('Chaveamento ainda não foi criado.');const d=s.getRange(2,1,l-1,CHAVEAMENTO_HEADERS_V004.length).getValues(),i=d.findIndex(r=>numero_(r[1])===jogo);if(i<0)throw Error('Jogo não encontrado.');const r=d[i],status=texto_(r[16]);if(!r[3]||!r[5])throw Error('As duas equipes ainda não estão definidas para esta partida.');if(status==='FINALIZADO')throw Error('Esta partida já foi finalizada.');const disponivel=r[18] instanceof Date?r[18]:(r[18]?new Date(r[18]):null),agora=new Date();if(disponivel&&agora.getTime()<disponivel.getTime())throw Error('Respeite o intervalo de 10 minutos. Esta partida estará liberada em '+formatarData_(disponivel)+'.');const vencedorId=resultado.vencedorLado===1?texto_(r[3]):texto_(r[5]);s.getRange(i+2,8,1,11).setValues([[s1a,s1b,s2a,s2b,s3a===null?'':s3a,s3b===null?'':s3b,resultado.sets1,resultado.sets2,vencedorId,'FINALIZADO',agora]]);const ng=numero_(r[20]),ns=numero_(r[21]);if(ng){const ni=d.findIndex(x=>numero_(x[1])===ng),t=lerEquipes_().filter(e=>e.id===vencedorId)[0];if(ni>=0&&t){const c=ns===1?4:6;s.getRange(ni+2,c,1,2).setValues([[t.id,nomeEquipe_(t)]])}}const dadosAtualizados=s.getRange(2,1,l-1,CHAVEAMENTO_HEADERS_V004.length).getValues(),intervalo=Number(obterConfig_().INTERVALO_ENTRE_PARTIDAS_MINUTOS||10),proxima=new Date(agora.getTime()+intervalo*60000);liberarProximaPartida_(dadosAtualizados,i,proxima);log_('PLACAR_REGISTRADO',texto_(r[0]),'PAINEL_WEB','ADMIN','Jogo '+jogo+' | '+s1a+'-'+s1b+', '+s2a+'-'+s2b+(s3a===null?'':', '+s3a+'-'+s3b)+' | Vencedor '+vencedorId);return{mensagem:'Placar registrado. Próxima partida liberada em '+intervalo+' minutos.',estado:obterEstadoAdmin_()}}