/** Embaralhamento, chaveamento, equipes gravadas e resultados */
function embaralharDeterministico_(lista,seed){const a=lista.slice();let e=parseInt(hash_(seed).slice(0,8),16)>>>0;function r(){e+=0x6D2B79F5;let t=e;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1)),x=a[i];a[i]=a[j];a[j]=x}return a}
function proximaPotenciaDois_(n){let p=1;while(p<Math.max(2,n))p*=2;return p}
function nomeFase_(size,round,total){const restantes=size/Math.pow(2,round+1);if(round===total-1)return'FINAL';if(restantes===2)return'SEMIFINAL';if(restantes===4)return'QUARTAS DE FINAL';if(restantes===8)return'OITAVAS DE FINAL';return'RODADA '+(round+1)}
function montarChaveamento_(equipes){const size=proximaPotenciaDois_(equipes.length),total=Math.log(size)/Math.log(2),slots=equipes.slice();while(slots.length<size)slots.push(null);const rounds=[];let jogo=1;for(let r=0;r<total;r++){const count=size/Math.pow(2,r+1),matches=[];for(let i=0;i<count;i++)matches.push({game:jogo++,roundIndex:r,phase:nomeFase_(size,r,total),team1:null,team2:null,team1Placeholder:'',team2Placeholder:'',winnerId:'',status:'AGUARDANDO',nextGame:0,nextSlot:0});rounds.push({index:r,name:nomeFase_(size,r,total),matches:matches})}for(let i=0;i<rounds[0].matches.length;i++){const m=rounds[0].matches[i];m.team1=slots[i*2];m.team2=slots[i*2+1];if(m.team1&&!m.team2){m.winnerId=m.team1.id;m.status='BYE'}else if(!m.team1&&m.team2){m.winnerId=m.team2.id;m.status='BYE'}else if(!m.team1&&!m.team2)m.status='VAZIO'}for(let r=0;r<rounds.length-1;r++)rounds[r].matches.forEach((m,i)=>{const next=rounds[r+1].matches[Math.floor(i/2)];m.nextGame=next.game;m.nextSlot=i%2===0?1:2;if(m.winnerId)atribuirVencedorMemoria_(rounds,m)});for(let r=1;r<rounds.length;r++)rounds[r].matches.forEach((m,i)=>{const p1=rounds[r-1].matches[i*2],p2=rounds[r-1].matches[i*2+1];if(!m.team1)m.team1Placeholder='Vencedor Jogo '+p1.game;if(!m.team2)m.team2Placeholder='Vencedor Jogo '+p2.game});return rounds}
function atribuirVencedorMemoria_(rounds,match){if(!match.nextGame||!match.winnerId)return;let next=null;for(let r=0;r<rounds.length;r++){next=rounds[r].matches.filter(m=>m.game===match.nextGame)[0];if(next)break}if(!next)return;const team=match.team1&&match.team1.id===match.winnerId?match.team1:match.team2;if(match.nextSlot===1)next.team1=team;else next.team2=team}
function nomeEquipe_(e){return e?e.adulto+' + '+e.crianca:''}
function gravarEquipes_(equipes){const s=aba_(VOLEI.SHEETS.EQUIPES);limparDadosAbaixoCabecalho_(VOLEI.SHEETS.EQUIPES,12);if(!equipes.length)return;s.getRange(2,1,equipes.length,12).setValues(equipes.map(e=>[e.id,e.adultoId,e.adulto,e.notaAdulto,e.indiceAdulto,e.criancaId,e.crianca,e.notaCrianca,e.indiceCrianca,e.indiceTotal,e.ordemBalanceamento,e.ordemChaveamento]))}
function gravarChaveamento_(sorteioId,rounds){const s=aba_(VOLEI.SHEETS.CHAVEAMENTO);if(s.getMaxColumns()<13)s.insertColumnsAfter(s.getMaxColumns(),13-s.getMaxColumns());s.getRange(1,1,1,13).setValues([VOLEI.HEADERS.CHAVEAMENTO]);limparDadosAbaixoCabecalho_(VOLEI.SHEETS.CHAVEAMENTO,13);const rows=[];rounds.forEach(round=>round.matches.forEach(m=>rows.push([sorteioId,m.game,m.phase,m.team1?m.team1.id:'',m.team1?nomeEquipe_(m.team1):m.team1Placeholder,m.team2?m.team2.id:'',m.team2?nomeEquipe_(m.team2):m.team2Placeholder,m.winnerId||'',m.status||'AGUARDANDO','',m.roundIndex,m.nextGame||'',m.nextSlot||''])));if(rows.length)s.getRange(2,1,rows.length,13).setValues(rows)}
function lerEquipes_(){const s=aba_(VOLEI.SHEETS.EQUIPES),l=s.getLastRow();if(l<2)return[];return s.getRange(2,1,l-1,12).getValues().filter(r=>r[0]).map(r=>({id:texto_(r[0]),adultoId:texto_(r[1]),adulto:texto_(r[2]),notaAdulto:numero_(r[3]),indiceAdulto:numero_(r[4]),criancaId:texto_(r[5]),crianca:texto_(r[6]),notaCrianca:numero_(r[7]),indiceCrianca:numero_(r[8]),indiceTotal:numero_(r[9]),ordemBalanceamento:numero_(r[10]),ordemChaveamento:numero_(r[11])}))}
function lerRounds_(){const s=aba_(VOLEI.SHEETS.CHAVEAMENTO),l=s.getLastRow();if(l<2)return[];const rows=s.getRange(2,1,l-1,13).getValues().filter(r=>r[0]),eq={};lerEquipes_().forEach(e=>eq[e.id]=e);const g={};rows.forEach(r=>{const i=numero_(r[10]);if(!g[i])g[i]={index:i,name:texto_(r[2])||'RODADA '+(i+1),matches:[]};g[i].matches.push({game:numero_(r[1]),roundIndex:i,phase:texto_(r[2]),team1:r[3]?eq[texto_(r[3])]||{id:texto_(r[3]),nome:texto_(r[4])}:null,team2:r[5]?eq[texto_(r[5])]||{id:texto_(r[5]),nome:texto_(r[6])}:null,team1Placeholder:!r[3]?texto_(r[4]):'',team2Placeholder:!r[5]?texto_(r[6]):'',winnerId:texto_(r[7]),status:texto_(r[8]),dataHora:r[9],nextGame:numero_(r[11]),nextSlot:numero_(r[12])})});return Object.keys(g).map(Number).sort((a,b)=>a-b).map(k=>g[k])}
function registrarResultado_(jogo,vencedorId){jogo=numero_(jogo);vencedorId=texto_(vencedorId);if(!jogo||!vencedorId)throw Error('Informe o jogo e o vencedor.');const s=aba_(VOLEI.SHEETS.CHAVEAMENTO),l=s.getLastRow();if(l<2)throw Error('Chaveamento ainda não foi criado.');const d=s.getRange(2,1,l-1,13).getValues(),i=d.findIndex(r=>numero_(r[1])===jogo);if(i<0)throw Error('Jogo não encontrado.');const r=d[i];if([texto_(r[3]),texto_(r[5])].indexOf(vencedorId)<0)throw Error('O vencedor não pertence a este jogo.');s.getRange(i+2,8,1,3).setValues([[vencedorId,'FINALIZADO',new Date()]]);const ng=numero_(r[11]),ns=numero_(r[12]);if(ng){const ni=d.findIndex(x=>numero_(x[1])===ng),t=lerEquipes_().filter(e=>e.id===vencedorId)[0];if(ni>=0&&t){const c=ns===1?4:6;s.getRange(ni+2,c,1,2).setValues([[t.id,nomeEquipe_(t)]])}}log_('RESULTADO_REGISTRADO',texto_(r[0]),'PAINEL_WEB','ADMIN','Jogo '+jogo+' | Vencedor '+vencedorId);return{mensagem:'Resultado registrado.',estado:obterEstadoAdmin_()}}